apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-1
  name: user-1-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
